### ISSUE TITLE
switching from qrcoder to qrsharp unable to display qrcode from base64

### ISSUE THREAD

**Issue by aitchdot** [superstreber3/QrSharp#2]
**Describe the bug**
OTP QRCode from Base64 Uri won't be displayed properly.

**To Reproduce**

ASP.NET WebApp Razor Page
.cshtml.cs
```
		public async Task<IActionResult> OnPost()
		{
			QRCodeIMG = await GetQRTask()
			return Page();
		}
```
```
public async Task<string> GetQRTask()
{
			string url = $"otpauth://totp/randomname:randomuser?secret=RANDOMSECRET";
			QrCodeData qrCodeData = QrCodeGenerator.CreateQrCode(url, QrCodeGenerator.ECCLevel.Q);
			BitmapByteQrCode qrCode = new(qrCodeData);
			byte[] qrCodeAsBitmapByteArr = qrCode.GetGraphic(10, SKColors.DarkGray.ToString(), SKColors.Orange.ToString());
			QRCodeImg = "data:image/png;base64," + Convert.ToBase64String(qrCodeAsBitmapByteArr);
			return QRCodeImg;
}
```
.cshtml
```
<img id="UserQR" src="@Model.QRCodeImg" alt="QRCodeImg"/>
```

**Expected behavior**

DIsplaying a QRCode

**Screenshots**

![Download](https://github.com/superstreber3/QrSharp/assets/104262846/40ad9bc5-15aa-44a4-8741-6d0dc6293235)

**Environment**
 - OS: Windows & Linux
 - .net version 6.0
 - QrSharp version latest

**Comment by superstreber3** [comment]
Hey @hakimdotdev 

Thanks for reporting :)
As you want to generate a base64 string you need to use the `Base64QrCode`. I have adjusted your code and tested it.

```cs
public async Task<string> GetQRTask()
{
    string url = $"otpauth://totp/randomname:randomuser?secret=RANDOMSECRET";
    QrCodeData qrCodeData = QrCodeGenerator.CreateQrCode(url, QrCodeGenerator.ECCLevel.Q);
    Base64QrCode qrCode = new(qrCodeData);
   var qrCodeAsBase64 = qrCode.GetGraphic(10, SKColors.DarkGray, SKColors.Orange);
    QRCodeImg = "data:image/png;base64," + qrCodeAsBase64;
    return QRCodeImg;
}
```
Result:
![image](https://github.com/superstreber3/QrSharp/assets/24655436/c4c67766-c123-48ae-ab54-a3a47ac4339e)

Please let me know if is working!

Note: BitmapByteQrCode expects the color as hex value.

**Comment by aitchdot** [comment]
Yes, it's working. Thanks alot.

**Comment by hakimdotdev** [comment]
Does not work for asp.net app in docker image 

```
TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.
QrSharp.QrCode.GetGraphic(int pixelsPerModule, SKColor darkColor, SKColor lightColor, bool drawQuietZones)
```

`TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.`
